logging:
  level.org.springframework.cloud: DEBUG

server:
  port: 9411

spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
  sleuth:
    enabled: false
    sampler:
      percentage: 1
zipkin:
  store:
    type: mem

logging.file: build/zipkin-server.log